os:
  - Visual Studio 2015
clone_depth: 1
configuration:
  - Debug
  - Release
platform:
  #- Win32
  - x64
environment:
  matrix:
    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
build_script: .appveyor/appveyor.bat
